CREATE TABLE IF NOT EXISTS IDN_SCIM_GROUP (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TENANT_ID INTEGER NOT NULL,
    ROLE_NAME VARCHAR(255) NOT NULL,
    ATTR_NAME VARCHAR(1024) NOT NULL,
    ATTR_VALUE VARCHAR(1024),
    PRIMARY KEY (ID)
);
